version: '3'
services:
    db:
        container_name: sf_mysql
        image: sephirauth/mysql:latest
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
        volumes:
        - mysql:/var/lib/mysql

    adminer:
        container_name: sf_adminer
        image: adminer:4.6
        ports:
            - 8080:8080

    php:
        image: php:7.2.3-fpm-alpine3.7
        container_name: sf_php
        volumes:
            - "./symfony:/home/docker:rw"
            - "./config/php/php.ini:/usr/local/etc/php/conf.d/custom.ini:ro"
        depends_on:
            - db
        working_dir: "/home/docker"

    nginx:
        container_name: sf_ngix
        image: nginx:1.13-alpine
        ports:
            - "80:80"
        depends_on:
            - php
        volumes:
            - "./symfony:/home/docker:ro"
            - "./config/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro"
volumes:
    mysql: